version: '3'
services:
  redis-sentinel-0:
    image: redis:${REDIS_VERSION}
    container_name: redis-sentinel-0
    command: redis-server /data/redis-sentinel.conf --sentinel
    ports:
    - "26380:26380"
    volumes:
    - ./data/sentinel-0:/data
  redis-sentinel-1:
    image: redis:${REDIS_VERSION}
    container_name: redis-sentinel-1
    command: redis-server /data/redis-sentinel.conf --sentinel
    ports:
    - "26381:26380"
    volumes:
    - ./data/sentinel-1:/data
  redis-sentinel-2:
    image: redis:${REDIS_VERSION}
    container_name: redis-sentinel-2
    command: redis-server /data/redis-sentinel.conf --sentinel
    ports:
    - "26382:26380"
    volumes:
    - ./data/sentinel-2:/data
  redis-master-0:
    image: redis:${REDIS_VERSION}
    container_name: redis-master-0
    command: redis-server /data/redis-master.conf
    ports:
    - "36380:6380"
    volumes:
    - ./data/master-0:/data
  redis-slave-0:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave-0
    command: redis-server /data/redis-slave.conf
    ports:
    - "36381:6380"
    volumes:
    - ./data/slave-0:/data
  redis-slave-1:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave-1
    command: redis-server /data/redis-slave.conf
    ports:
    - "36382:6380"
    volumes:
    - ./data/slave-1:/data

networks:
  default:
    external:
      name: ${NETWORK}