version: '3'
services:
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx-1.18
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./cert:/etc/cert"

networks:
  default:
    external:
      name: docker-lab