version: "3"
services: 
  mysql: 
    image: mysql:5.7
    container_name: mysql57
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - "./conf/my.cnf:/etc/my.cnf"
      - "./data:/var/lib/mysql"
    
networks:
  default:
    external:
      name: docker-lab